name: Building

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'oracle'
        cache: gradle

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        cache: true

    - name: Install packets
      run: flutter pub get

    - name: Run Test
      run: flutter test

    - name: Build Android
      run: flutter build apk

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android
        path: |
          build/app/outputs/apk
